legislative_sessions update
washabstract/cyclades-openstates-core pull request #12
Opened 2024-10-30 00:45 UTC by Desitrain22

This change looks to re-implement `legislative_sessions` as a property (as opposed to a manually defined list), and retire the legacy `legislative_sessions` as `historical_legislative_sessions`. We include the ability to `opt_for_new` to give us flexibility when re-writing sessions, custom backfill and more. This is particularly relevant when additions are made to the main openstates core and scrapers that include new session information.

2024-11-01 18:52 UTC, jessicabowden submitted a review, later dismissed

2024-11-20 18:17 UTC, jessicabowden requested changes

2024-11-21 22:08 UTC, Desitrain22 commented on openstates/scrape/jurisdiction.py
> +            return []
Added a print statement over logging -- not sure if importing and spinning up a logging instance here is best. I fiddled a bit with trying to pass in a logger to the State but that created some problems with the scoping of the 'openstates' scraper

2024-11-25 16:39 UTC, jessicabowden approved these changes

2024-11-25 19:39 UTC, jessicabowden approved these changes

2024-11-25 20:53 UTC, merged